appName: osiris-ingress-adapter-jao
environment: test
image:
  repository: transform-ingress2event-time
  tag: latest
schedule: "0 1 * * *"
concurrencyPolicy: "Allow"
config:
  conf.ini: |
    [Logging]
    configuration_file = log.conf

    [Azure Storage]
    ingress_url = <ingress_url>
    filesystem_name = <datasets>

    [Datasets]
    source = <source>

    [JAO Server]
    server_url = <url>

    [JAO Values]
    default_date = 2020-01-01
  log.conf: |
    [loggers]
    keys=root
    [handlers]
    keys=consoleHandler,fileHandler
    [formatters]
    keys=fileFormatter,consoleFormatter
    [logger_root]
    level=DEBUG
    handlers=consoleHandler
    [handler_consoleHandler]
    class=StreamHandler
    formatter=consoleFormatter
    args=(sys.stdout,)
    [handler_fileHandler]
    class=FileHandler
    formatter=fileFormatter
    args=('logfile.log',)
    [formatter_fileFormatter]
    format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    datefmt=
    [formatter_consoleFormatter]
    format=%(levelname)s: %(name)s - %(message)s
